{
 "title": "DataDomain - Dashboard",
 "tags": [ "DD Dashboard" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Datadomain Dashboards",
   "type": "dashlist",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Alerts on DD",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "DDAlertList",
     "select": [
      [
       { "params": [ "activealert" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Dedupe",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "TierCapacityUsageCompressionFactor",
     "select": [
      [
       { "params": [ "CompressionFactor" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Used Capacity (TB)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "TierCapacityUsagePhysicalCapacity",
     "select": [
      [
       { "params": [ "PhysicalCapacityTotal" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}